Lesson 15
Nichyk/Study_practice pull request #14
Opened 2023-04-15 14:08 UTC by Nichyk

add all solutions for task 3

2023-04-21 12:03 UTC, desireoftheother requested changes
Думаю, потрібна одна невелика зміна. Деталі в коментарях.

2023-04-21 12:03 UTC, desireoftheother commented on Lesson 15/task_3.py
> +        self.current_channel_index = n - 1
Якщо ти зробиш цю зміну, а потім викличеш current_channel, то буде помилка. Треба задавати current_channel_index в рамках try-except блоку. Щоб, якщо що, не міняти цю змінну.

2023-04-21 12:03 UTC, desireoftheother commented on Lesson 15/task_3.py
> +        self.current_channel_index = (self.current_channel_index + 1) % len(self.channels)
Класний підхід, гарне рішення.

2023-04-29 04:42 UTC, Nichyk commented on Lesson 15/task_3.py
> +        self.current_channel_index = n - 1
Вніс зміни за допомогою if

2023-05-30 01:09 UTC, desireoftheother approved these changes
LGTM.

2023-05-30 01:09 UTC, desireoftheother commented on Lesson 15/task_3.py
> +            return "Yes" if channel in self.channels else "No"
Можна повертати просто булеве значення, на майбутнє я б так і робив

2023-05-30 13:54 UTC, merged