Lesson 17
Nichyk/Study_practice pull request #16
Opened 2023-04-27 15:46 UTC by Nichyk

2023-04-28 13:18 UTC, desireoftheother requested changes
У Fraction не імплементовано порівняння.

2023-04-28 13:18 UTC, desireoftheother commented on Lesson 17/task_3.py
> +class Fraction:
А порівняння?)

2023-04-29 05:09 UTC, Nichyk commented on Lesson 17/task_3.py
> +class Fraction:
Додав

2023-05-30 01:12 UTC, desireoftheother approved these changes

2023-05-30 01:12 UTC, desireoftheother commented on Lesson 17/task_3.py
> +        return self.nom / self.denom < other.nom / other.denom
Окей, це рішення, хоча, звісно, порівняння чисельників при переході до спільного знаменника було б банально точніше

2023-05-30 13:56 UTC, merged